import { ethers } from "hardhat";
import * as fs from "fs";

interface DeploymentInfo {
  usdc: string;
  router: string;
  deployer: string;
  merchant: string;
  agent: string;
  facilitator: string;
  chainId: number;
  network: string;
}

async function main(): Promise<void> {
  const [deployer, merchant, agent, facilitator] = await ethers.getSigners();
  const network = await ethers.provider.getNetwork();

  console.log("=== Helix402 Local Deployment ===\n");
  console.log("Network:", network.name, "| Chain ID:", network.chainId.toString());
  console.log("Deployer:", deployer.address);

  // 1. Deploy MockUSDC (with EIP-3009)
  const MockUSDC = await ethers.getContractFactory("MockUSDC");
  const usdc = await MockUSDC.deploy();
  await usdc.waitForDeployment();
  const usdcAddress = await usdc.getAddress();
  console.log("\n✅ MockUSDC deployed:", usdcAddress);

  // 2. Deploy Helix402Router (atomic fee split)
  const Router = await ethers.getContractFactory("Helix402Router");
  const router = await Router.deploy(usdcAddress, facilitator.address, 100); // 1% fee
  await router.waitForDeployment();
  const routerAddress = await router.getAddress();
  console.log("✅ Helix402Router deployed:", routerAddress, "(1% fee →", facilitator.address + ")");

  // 3. Fund agent with USDC
  const agentFund = 1000n * 10n ** 6n; // 1000 USDC
  await usdc.mint(agent.address, agentFund);
  console.log(`✅ Agent funded: ${agent.address} → 1000 USDC`);

  // 4. Verify
  console.log(`✅ Facilitator: ${facilitator.address} (receives fees)`);
  const domainSep = await usdc.DOMAIN_SEPARATOR();
  console.log(`✅ EIP-3009 active: DOMAIN_SEPARATOR = ${domainSep.slice(0, 18)}...`);

  // 5. Write deployment info
  const info: DeploymentInfo = {
    usdc: usdcAddress,
    router: routerAddress,
    deployer: deployer.address,
    merchant: merchant.address,
    agent: agent.address,
    facilitator: facilitator.address,
    chainId: Number(network.chainId),
    network: network.name === "unknown" ? "localhost" : network.name,
  };

  fs.writeFileSync("./deployment.json", JSON.stringify(info, null, 2));
  console.log("\n📄 deployment.json written");

  // 6. Print env vars
  console.log("\n=== Gateway Environment ===");
  console.log(`USDC_ADDRESS=${usdcAddress}`);
  console.log(`ROUTER_ADDRESS=${routerAddress}`);
  console.log(`RPC_URL=http://127.0.0.1:8545`);

  // Write .env.local
  const envContent = [
    `# Auto-generated by deploy script — ${new Date().toISOString()}`,
    `USDC_ADDRESS=${usdcAddress}`,
    `ROUTER_ADDRESS=${routerAddress}`,
    `RPC_URL=http://127.0.0.1:8545`,
    `JWT_SECRET=dev-secret-change-in-production`,
    `PORT=3001`,
    `FACILITATOR_PRIVATE_KEY=0xa267530f49f8280200edf313ee7af6b827f2a8bce2897751d06a843f644967b1`,
    `AGENT_PRIVATE_KEY=0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a`,
    `MERCHANT_WALLET=${merchant.address}`,
    `PLATFORM_FEE_ENABLED=true`,
    `PLATFORM_FEE_BPS=100`,
  ].join("\n");

  fs.writeFileSync("../../.env.local", envContent);
  console.log("📄 .env.local written");

  console.log("\n=== Ready ===");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
